---
- name: Disable the default site
  file:
    path: "{{nginx_conf_dir}}/sites-enabled/{{item}}"
    state: absent
  with_items:
    - default
    - default.conf
  notify:
  - reload nginx

- name: Remove the default configuration
  file:
    path: "{{nginx_conf_dir}}/conf.d/default.conf"
    state: absent
  when: >
    'default' not in nginx_configs.keys()
  notify:
  - reload nginx
